services:
  - docker

before_install:
  - docker build \
    --build-arg user=$USER \
    -t $USER/archlinux .travis/

script:
  - docker run --rm \
    -v $TRAVIS_BUILD_DIR:/home/$USER/pkgbuilds \
    $USER/archlinux \
    .travis/test-all.sh

deploy:
  provider: script
  script: .travis/deploy_changed.sh
  skip_cleanup: true
  on:
    branch: master
    condition: when things changed?
